// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgK0g6XshGxkEYttloUOtyRdedTUqHZrE',
    appId: '1:702847166853:web:acb692ef5721320352fcec',
    messagingSenderId: '702847166853',
    projectId: 'carelink-26412',
    authDomain: 'carelink-26412.firebaseapp.com',
    storageBucket: 'carelink-26412.firebasestorage.app',
    measurementId: 'G-KXZPWT91CD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGeZ_5sHcVQ_Ubp-syfLODSRbfQpxSNpY',
    appId: '1:702847166853:android:18143a5b88c791a552fcec',
    messagingSenderId: '702847166853',
    projectId: 'carelink-26412',
    storageBucket: 'carelink-26412.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlMK74NaZJ2NSszio4lOYi4u6TZsbX4rc',
    appId: '1:702847166853:ios:39d7d9ea7211bbdc52fcec',
    messagingSenderId: '702847166853',
    projectId: 'carelink-26412',
    storageBucket: 'carelink-26412.firebasestorage.app',
    iosBundleId: 'com.example.carelink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlMK74NaZJ2NSszio4lOYi4u6TZsbX4rc',
    appId: '1:702847166853:ios:39d7d9ea7211bbdc52fcec',
    messagingSenderId: '702847166853',
    projectId: 'carelink-26412',
    storageBucket: 'carelink-26412.firebasestorage.app',
    iosBundleId: 'com.example.carelink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgK0g6XshGxkEYttloUOtyRdedTUqHZrE',
    appId: '1:702847166853:web:ffafdf3cbf00013d52fcec',
    messagingSenderId: '702847166853',
    projectId: 'carelink-26412',
    authDomain: 'carelink-26412.firebaseapp.com',
    storageBucket: 'carelink-26412.firebasestorage.app',
    measurementId: 'G-MT14WTLXDD',
  );
}
